import { MatchType, Productivity } from '@prisma/client';

/**
 * The app and site categories a new install starts with — what counts as
 * work, what does not. The owner edits them afterwards on Settings → Apps &
 * sites. Used by the setup wizard and by `prisma/seed.ts`.
 *
 * Each rule: [match type, pattern, display name, category, priority?].
 */
export type CategoryRule = [MatchType, string, string, Productivity, number?];

export const DEFAULT_APP_CATEGORIES: CategoryRule[] = [
  // ── development ───────────────────────────────────────────────
  [MatchType.process, 'code.exe', 'Visual Studio Code', Productivity.productive],
  [MatchType.process, 'devenv.exe', 'Visual Studio', Productivity.productive],
  [MatchType.process, 'rider64.exe', 'JetBrains Rider', Productivity.productive],
  [MatchType.process, 'webstorm64.exe', 'WebStorm', Productivity.productive],
  [MatchType.process, 'pycharm64.exe', 'PyCharm', Productivity.productive],
  [MatchType.process, 'idea64.exe', 'IntelliJ IDEA', Productivity.productive],
  [MatchType.process, 'sublime_text.exe', 'Sublime Text', Productivity.productive],
  [MatchType.process, 'notepad++.exe', 'Notepad++', Productivity.productive],
  [MatchType.process, 'windowsterminal.exe', 'Windows Terminal', Productivity.productive],
  [MatchType.process, 'powershell.exe', 'PowerShell', Productivity.productive],
  [MatchType.process, 'cmd.exe', 'Command Prompt', Productivity.productive],
  [MatchType.process, 'git-bash.exe', 'Git Bash', Productivity.productive],
  [MatchType.process, 'docker desktop.exe', 'Docker Desktop', Productivity.productive],
  [MatchType.process, 'postman.exe', 'Postman', Productivity.productive],
  [MatchType.process, 'insomnia.exe', 'Insomnia', Productivity.productive],
  [MatchType.process, 'datagrip64.exe', 'DataGrip', Productivity.productive],
  [MatchType.process, 'ssms.exe', 'SQL Server Mgmt Studio', Productivity.productive],
  [MatchType.process, 'pgadmin4.exe', 'pgAdmin', Productivity.productive],
  [MatchType.process, 'mysqlworkbench.exe', 'MySQL Workbench', Productivity.productive],
  [MatchType.process, 'sourcetree.exe', 'Sourcetree', Productivity.productive],
  [MatchType.process, 'gitkraken.exe', 'GitKraken', Productivity.productive],
  [MatchType.domain, 'github.com', 'GitHub', Productivity.productive],
  [MatchType.domain, 'gitlab.com', 'GitLab', Productivity.productive],
  [MatchType.domain, 'bitbucket.org', 'Bitbucket', Productivity.productive],
  [MatchType.domain, 'stackoverflow.com', 'Stack Overflow', Productivity.productive],
  [MatchType.domain, 'developer.mozilla.org', 'MDN', Productivity.productive],
  [MatchType.domain, 'npmjs.com', 'npm', Productivity.productive],
  [MatchType.domain, 'nuget.org', 'NuGet', Productivity.productive],
  [MatchType.domain, 'docs.microsoft.com', 'Microsoft Docs', Productivity.productive],
  [MatchType.domain, 'learn.microsoft.com', 'Microsoft Learn', Productivity.productive],
  [MatchType.domain, 'vercel.com', 'Vercel', Productivity.productive],
  [MatchType.domain, 'netlify.com', 'Netlify', Productivity.productive],
  [MatchType.domain, 'digitalocean.com', 'DigitalOcean', Productivity.productive],
  [MatchType.domain, 'aws.amazon.com', 'AWS', Productivity.productive],
  [MatchType.domain, 'console.cloud.google.com', 'Google Cloud', Productivity.productive],
  [MatchType.domain, 'chatgpt.com', 'ChatGPT', Productivity.productive],
  [MatchType.domain, 'claude.ai', 'Claude', Productivity.productive],

  // ── design ────────────────────────────────────────────────────
  [MatchType.process, 'photoshop.exe', 'Adobe Photoshop', Productivity.productive],
  [MatchType.process, 'illustrator.exe', 'Adobe Illustrator', Productivity.productive],
  [MatchType.process, 'indesign.exe', 'Adobe InDesign', Productivity.productive],
  [MatchType.process, 'afterfx.exe', 'After Effects', Productivity.productive],
  [MatchType.process, 'adobe premiere pro.exe', 'Premiere Pro', Productivity.productive],
  [MatchType.process, 'figma.exe', 'Figma', Productivity.productive],
  [MatchType.process, 'coreldrw.exe', 'CorelDRAW', Productivity.productive],
  [MatchType.process, 'blender.exe', 'Blender', Productivity.productive],
  [MatchType.domain, 'figma.com', 'Figma', Productivity.productive],
  [MatchType.domain, 'canva.com', 'Canva', Productivity.productive],
  [MatchType.domain, 'dribbble.com', 'Dribbble', Productivity.productive],
  [MatchType.domain, 'behance.net', 'Behance', Productivity.productive],
  [MatchType.domain, 'unsplash.com', 'Unsplash', Productivity.productive],

  // ── office and documents ──────────────────────────────────────
  [MatchType.process, 'excel.exe', 'Microsoft Excel', Productivity.productive],
  [MatchType.process, 'winword.exe', 'Microsoft Word', Productivity.productive],
  [MatchType.process, 'powerpnt.exe', 'PowerPoint', Productivity.productive],
  [MatchType.process, 'outlook.exe', 'Outlook', Productivity.productive],
  [MatchType.process, 'onenote.exe', 'OneNote', Productivity.productive],
  [MatchType.process, 'acrobat.exe', 'Adobe Acrobat', Productivity.productive],
  [MatchType.process, 'acrord32.exe', 'Acrobat Reader', Productivity.productive],
  [MatchType.domain, 'docs.google.com', 'Google Docs', Productivity.productive],
  [MatchType.domain, 'sheets.google.com', 'Google Sheets', Productivity.productive],
  [MatchType.domain, 'drive.google.com', 'Google Drive', Productivity.productive],
  [MatchType.domain, 'mail.google.com', 'Gmail', Productivity.productive],
  [MatchType.domain, 'outlook.office.com', 'Outlook Web', Productivity.productive],
  [MatchType.domain, 'notion.so', 'Notion', Productivity.productive],
  [MatchType.domain, 'atlassian.net', 'Jira / Confluence', Productivity.productive],
  [MatchType.domain, 'trello.com', 'Trello', Productivity.productive],
  [MatchType.domain, 'asana.com', 'Asana', Productivity.productive],
  [MatchType.domain, 'clickup.com', 'ClickUp', Productivity.productive],

  // ── communication (work, but hard to measure) ─────────────────
  [MatchType.process, 'ms-teams.exe', 'Microsoft Teams', Productivity.productive],
  [MatchType.process, 'teams.exe', 'Microsoft Teams', Productivity.productive],
  [MatchType.process, 'slack.exe', 'Slack', Productivity.productive],
  [MatchType.process, 'zoom.exe', 'Zoom', Productivity.productive],
  [MatchType.process, 'skype.exe', 'Skype', Productivity.neutral],
  [MatchType.domain, 'meet.google.com', 'Google Meet', Productivity.productive],
  [MatchType.domain, 'zoom.us', 'Zoom', Productivity.productive],
  [MatchType.domain, 'slack.com', 'Slack', Productivity.productive],
  [MatchType.domain, 'web.whatsapp.com', 'WhatsApp Web', Productivity.neutral],

  // ── neutral ───────────────────────────────────────────────────
  [MatchType.process, 'explorer.exe', 'File Explorer', Productivity.neutral],
  [MatchType.process, 'chrome.exe', 'Google Chrome', Productivity.neutral, 200],
  [MatchType.process, 'msedge.exe', 'Microsoft Edge', Productivity.neutral, 200],
  [MatchType.process, 'firefox.exe', 'Mozilla Firefox', Productivity.neutral, 200],
  [MatchType.process, 'calc.exe', 'Calculator', Productivity.neutral],
  [MatchType.process, 'notepad.exe', 'Notepad', Productivity.neutral],
  [MatchType.process, 'snippingtool.exe', 'Snipping Tool', Productivity.neutral],
  [MatchType.domain, 'google.com', 'Google Search', Productivity.neutral],
  [MatchType.domain, 'bing.com', 'Bing', Productivity.neutral],
  [MatchType.domain, 'wikipedia.org', 'Wikipedia', Productivity.neutral],
  [MatchType.domain, 'linkedin.com', 'LinkedIn', Productivity.neutral],
  [MatchType.domain, 'prothomalo.com', 'Prothom Alo', Productivity.neutral],
  [MatchType.domain, 'bdnews24.com', 'bdnews24', Productivity.neutral],

  // ── unproductive ──────────────────────────────────────────────
  [MatchType.domain, 'facebook.com', 'Facebook', Productivity.unproductive],
  [MatchType.domain, 'messenger.com', 'Messenger', Productivity.unproductive],
  [MatchType.domain, 'instagram.com', 'Instagram', Productivity.unproductive],
  [MatchType.domain, 'tiktok.com', 'TikTok', Productivity.unproductive],
  [MatchType.domain, 'x.com', 'X (Twitter)', Productivity.unproductive],
  [MatchType.domain, 'twitter.com', 'Twitter', Productivity.unproductive],
  [MatchType.domain, 'youtube.com', 'YouTube', Productivity.unproductive],
  [MatchType.domain, 'netflix.com', 'Netflix', Productivity.unproductive],
  [MatchType.domain, 'hoichoi.tv', 'Hoichoi', Productivity.unproductive],
  [MatchType.domain, 'reddit.com', 'Reddit', Productivity.unproductive],
  [MatchType.domain, 'pinterest.com', 'Pinterest', Productivity.unproductive],
  [MatchType.domain, 'twitch.tv', 'Twitch', Productivity.unproductive],
  [MatchType.domain, 'daraz.com.bd', 'Daraz', Productivity.unproductive],
  [MatchType.domain, 'amazon.com', 'Amazon', Productivity.unproductive],
  [MatchType.domain, 'cricbuzz.com', 'Cricbuzz', Productivity.unproductive],
  [MatchType.domain, 'espncricinfo.com', 'ESPNcricinfo', Productivity.unproductive],
  [MatchType.process, 'steam.exe', 'Steam', Productivity.unproductive],
  [MatchType.process, 'epicgameslauncher.exe', 'Epic Games', Productivity.unproductive],
  [MatchType.process, 'spotify.exe', 'Spotify', Productivity.unproductive],
  [MatchType.process, 'vlc.exe', 'VLC Player', Productivity.unproductive],
];
